name: complete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  google_sign_in: ^6.2.1
  http: ^1.4.0
  html: ^0.15.1
  url_launcher: ^6.2.6
  flutter_vector_icons: ^2.0.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0
  path_provider: ^2.1.2
  google_generative_ai: ^0.2.0
  flutter_dotenv: ^5.1.0
  file_picker: ^6.2.1
  open_file: ^3.3.2
  mime: ^1.0.5
  share_plus: ^7.2.2
  shared_preferences: ^2.2.3


  # Cloud Firestore (for storing user data)
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/legal_web_1.png
    - .env
